# Form implementation generated from reading ui file 'C:\CSDL_doan\Phieukhu.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlantInfoDialog(object):
    def setupUi(self, PlantInfoDialog):
        PlantInfoDialog.setObjectName("PlantInfoDialog")
        PlantInfoDialog.resize(700, 700)
        self.mainLayout = QtWidgets.QVBoxLayout(PlantInfoDialog)
        self.mainLayout.setContentsMargins(40, 30, 40, 30)
        self.mainLayout.setSpacing(20)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLabel = QtWidgets.QLabel(parent=PlantInfoDialog)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(spacerItem)
        self.infoGroupBox = QtWidgets.QGroupBox(parent=PlantInfoDialog)
        self.infoGroupBox.setObjectName("infoGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.infoGroupBox)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.idLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.idLabel.setObjectName("idLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.idLabel)
        self.idInput = QtWidgets.QLineEdit(parent=self.infoGroupBox)
        self.idInput.setEnabled(False)
        self.idInput.setObjectName("idInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.idInput)
        self.nameLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nameLabel)
        self.nameInput = QtWidgets.QLineEdit(parent=self.infoGroupBox)
        self.nameInput.setObjectName("nameInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameInput)
        self.scientificNameLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.scientificNameLabel.setObjectName("scientificNameLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.scientificNameLabel)
        self.scientificNameInput = QtWidgets.QLineEdit(parent=self.infoGroupBox)
        self.scientificNameInput.setObjectName("scientificNameInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.scientificNameInput)
        self.familyLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.familyLabel.setObjectName("familyLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.familyLabel)
        self.familyInput = QtWidgets.QLineEdit(parent=self.infoGroupBox)
        self.familyInput.setObjectName("familyInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.familyInput)
        self.characteristicsLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.characteristicsLabel.setObjectName("characteristicsLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.characteristicsLabel)
        self.characteristicsInput = QtWidgets.QTextEdit(parent=self.infoGroupBox)
        self.characteristicsInput.setMaximumSize(QtCore.QSize(16777215, 100))
        self.characteristicsInput.setObjectName("characteristicsInput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.characteristicsInput)
        self.mainLayout.addWidget(self.infoGroupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(spacerItem1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.cancelButton = QtWidgets.QPushButton(parent=PlantInfoDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(120, 45))
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.saveButton = QtWidgets.QPushButton(parent=PlantInfoDialog)
        self.saveButton.setMinimumSize(QtCore.QSize(120, 45))
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem3)
        self.mainLayout.addLayout(self.buttonLayout)

        self.retranslateUi(PlantInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(PlantInfoDialog)

    def retranslateUi(self, PlantInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        PlantInfoDialog.setWindowTitle(_translate("PlantInfoDialog", "PHIẾU THÔNG TIN LOÀI THỰC VẬT"))
        PlantInfoDialog.setStyleSheet(_translate("PlantInfoDialog", "\n"
"    QDialog {\n"
"        background-color: #f5f6fa;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"        font-weight: bold;\n"
"    }\n"
"   "))
        self.titleLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 22px; font-weight: bold; color: #2c3e50; padding: 10px; background-color: #3498db; color: white; border-radius: 8px;"))
        self.titleLabel.setText(_translate("PlantInfoDialog", "PHIẾU THÔNG TIN KHU TRƯNG BÀY"))
        self.infoGroupBox.setStyleSheet(_translate("PlantInfoDialog", "\n"
"       QGroupBox {\n"
"           font-weight: bold;\n"
"           font-size: 14px;\n"
"           color: #2c3e50;\n"
"           border: 2px solid #bdc3c7;\n"
"           border-radius: 8px;\n"
"           margin-top: 15px;\n"
"           padding-top: 10px;\n"
"           background-color: white;\n"
"       }\n"
"       QGroupBox::title {\n"
"           subcontrol-origin: margin;\n"
"           left: 20px;\n"
"           padding: 0 10px;\n"
"           background-color: white;\n"
"       }\n"
"      "))
        self.infoGroupBox.setTitle(_translate("PlantInfoDialog", "THÔNG TIN CHI TIẾT"))
        self.idLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.idLabel.setText(_translate("PlantInfoDialog", "Mã khu"))
        self.idInput.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #3498db; border-radius: 4px; background-color: #ecf0f1; color: #2c3e50; font-weight: bold; font-size: 13px;"))
        self.idInput.setText(_translate("PlantInfoDialog", "LO001"))
        self.nameLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.nameLabel.setText(_translate("PlantInfoDialog", "Tên khu"))
        self.nameInput.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #bdc3c7; border-radius: 4px; font-size: 13px;"))
        self.nameInput.setPlaceholderText(_translate("PlantInfoDialog", "Nhập tên khu"))
        self.scientificNameLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.scientificNameLabel.setText(_translate("PlantInfoDialog", "Vị trí"))
        self.scientificNameInput.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #bdc3c7; border-radius: 4px; font-size: 13px;"))
        self.scientificNameInput.setPlaceholderText(_translate("PlantInfoDialog", "Nhập vị trí"))
        self.familyLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.familyLabel.setText(_translate("PlantInfoDialog", "Diện tích (m^2)"))
        self.familyInput.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #bdc3c7; border-radius: 4px; font-size: 13px;"))
        self.familyInput.setPlaceholderText(_translate("PlantInfoDialog", "Nhập diện tích"))
        self.characteristicsLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px; alignment: top;"))
        self.characteristicsLabel.setText(_translate("PlantInfoDialog", "Mô tả"))
        self.characteristicsInput.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #bdc3c7; border-radius: 4px; font-size: 13px;"))
        self.characteristicsInput.setPlaceholderText(_translate("PlantInfoDialog", "Nhập mô tả"))
        self.cancelButton.setStyleSheet(_translate("PlantInfoDialog", "\n"
"         QPushButton {\n"
"             background-color: #95a5a6;\n"
"             color: white;\n"
"             border: none;\n"
"             border-radius: 6px;\n"
"             font-weight: bold;\n"
"             font-size: 14px;\n"
"             padding: 10px;\n"
"         }\n"
"         QPushButton:hover {\n"
"             background-color: #7f8c8d;\n"
"         }\n"
"         QPushButton:pressed {\n"
"             background-color: #6c7a7a;\n"
"         }\n"
"        "))
        self.cancelButton.setText(_translate("PlantInfoDialog", "Hủy"))
        self.saveButton.setStyleSheet(_translate("PlantInfoDialog", "\n"
"         QPushButton {\n"
"             background-color: #27ae60;\n"
"             color: white;\n"
"             border: none;\n"
"             border-radius: 6px;\n"
"             font-weight: bold;\n"
"             font-size: 14px;\n"
"             padding: 10px;\n"
"         }\n"
"         QPushButton:hover {\n"
"             background-color: #219a52;\n"
"         }\n"
"         QPushButton:pressed {\n"
"             background-color: #1e8449;\n"
"         }\n"
"        "))
        self.saveButton.setText(_translate("PlantInfoDialog", "Lưu thông tin"))
