# Form implementation generated from reading ui file 'C:\CSDL_doan\Phieunhanvien.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlantInfoDialog(object):
    def setupUi(self, PlantInfoDialog):
        PlantInfoDialog.setObjectName("PlantInfoDialog")
        PlantInfoDialog.resize(700, 750)
        self.mainLayout = QtWidgets.QVBoxLayout(PlantInfoDialog)
        self.mainLayout.setContentsMargins(40, 30, 40, 30)
        self.mainLayout.setSpacing(20)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLabel = QtWidgets.QLabel(parent=PlantInfoDialog)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        self.infoGroupBox = QtWidgets.QGroupBox(parent=PlantInfoDialog)
        self.infoGroupBox.setObjectName("infoGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.infoGroupBox)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.idLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.idLabel.setObjectName("idLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.idLabel)
        self.idInput = QtWidgets.QLineEdit(parent=self.infoGroupBox)
        self.idInput.setEnabled(False)
        self.idInput.setObjectName("idInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.idInput)
        self.nameLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nameLabel)
        self.nameInput = QtWidgets.QLineEdit(parent=self.infoGroupBox)
        self.nameInput.setObjectName("nameInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameInput)
        self.dobLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.dobLabel.setObjectName("dobLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dobLabel)
        self.dobInput = QtWidgets.QLineEdit(parent=self.infoGroupBox)
        self.dobInput.setObjectName("dobInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dobInput)
        self.genderLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.genderLabel.setObjectName("genderLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.genderLabel)
        self.genderCombo = QtWidgets.QComboBox(parent=self.infoGroupBox)
        self.genderCombo.setObjectName("genderCombo")
        self.genderCombo.addItem("")
        self.genderCombo.addItem("")
        self.genderCombo.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.genderCombo)
        self.phoneLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.phoneLabel.setObjectName("phoneLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.phoneLabel)
        self.phoneInput = QtWidgets.QLineEdit(parent=self.infoGroupBox)
        self.phoneInput.setObjectName("phoneInput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phoneInput)
        self.emailLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.emailLabel)
        self.emailInput = QtWidgets.QLineEdit(parent=self.infoGroupBox)
        self.emailInput.setObjectName("emailInput")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.emailInput)
        self.positionLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.positionLabel.setObjectName("positionLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.positionLabel)
        self.positionCombo = QtWidgets.QComboBox(parent=self.infoGroupBox)
        self.positionCombo.setObjectName("positionCombo")
        self.positionCombo.addItem("")
        self.positionCombo.addItem("")
        self.positionCombo.addItem("")
        self.positionCombo.addItem("")
        self.positionCombo.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.positionCombo)
        self.areaLabel = QtWidgets.QLabel(parent=self.infoGroupBox)
        self.areaLabel.setObjectName("areaLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.areaLabel)
        self.areaInput = QtWidgets.QLineEdit(parent=self.infoGroupBox)
        self.areaInput.setObjectName("areaInput")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.areaInput)
        self.mainLayout.addWidget(self.infoGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(spacerItem)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.cancelButton = QtWidgets.QPushButton(parent=PlantInfoDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(120, 45))
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.saveButton = QtWidgets.QPushButton(parent=PlantInfoDialog)
        self.saveButton.setMinimumSize(QtCore.QSize(120, 45))
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.mainLayout.addLayout(self.buttonLayout)

        self.retranslateUi(PlantInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(PlantInfoDialog)

    def retranslateUi(self, PlantInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        PlantInfoDialog.setWindowTitle(_translate("PlantInfoDialog", "PHIẾU THÔNG TIN NHÂN VIÊN"))
        PlantInfoDialog.setStyleSheet(_translate("PlantInfoDialog", "\n"
"    QDialog {\n"
"        background-color: #f5f6fa;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"        font-weight: bold;\n"
"    }\n"
"   "))
        self.titleLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 22px; font-weight: bold; color: #2c3e50; padding: 10px; background-color: #3498db; color: white; border-radius: 8px;"))
        self.titleLabel.setText(_translate("PlantInfoDialog", "PHIẾU THÔNG TIN NHÂN VIÊN"))
        self.infoGroupBox.setStyleSheet(_translate("PlantInfoDialog", "\n"
"       QGroupBox {\n"
"           font-weight: bold;\n"
"           font-size: 14px;\n"
"           color: #2c3e50;\n"
"           border: 2px solid #bdc3c7;\n"
"           border-radius: 8px;\n"
"           margin-top: 15px;\n"
"           padding-top: 10px;\n"
"           background-color: white;\n"
"       }\n"
"       QGroupBox::title {\n"
"           subcontrol-origin: margin;\n"
"           left: 20px;\n"
"           padding: 0 10px;\n"
"           background-color: white;\n"
"       }\n"
"      "))
        self.infoGroupBox.setTitle(_translate("PlantInfoDialog", "THÔNG TIN CHI TIẾT"))
        self.idLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.idLabel.setText(_translate("PlantInfoDialog", "Mã nhân viên"))
        self.idInput.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #3498db; border-radius: 4px; background-color: #ecf0f1; color: #2c3e50; font-weight: bold; font-size: 13px;"))
        self.idInput.setText(_translate("PlantInfoDialog", "NV001"))
        self.nameLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.nameLabel.setText(_translate("PlantInfoDialog", "Họ và tên *"))
        self.nameInput.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #e74c3c; border-radius: 4px; font-size: 13px;"))
        self.nameInput.setPlaceholderText(_translate("PlantInfoDialog", "Nhập họ và tên"))
        self.dobLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.dobLabel.setText(_translate("PlantInfoDialog", "Ngày sinh"))
        self.dobInput.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #bdc3c7; border-radius: 4px; font-size: 13px;"))
        self.dobInput.setPlaceholderText(_translate("PlantInfoDialog", "dd/mm/yyyy"))
        self.genderLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.genderLabel.setText(_translate("PlantInfoDialog", "Giới tính"))
        self.genderCombo.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #bdc3c7; border-radius: 4px; font-size: 13px;"))
        self.genderCombo.setItemText(0, _translate("PlantInfoDialog", "Nam"))
        self.genderCombo.setItemText(1, _translate("PlantInfoDialog", "Nữ"))
        self.genderCombo.setItemText(2, _translate("PlantInfoDialog", "Khác"))
        self.phoneLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.phoneLabel.setText(_translate("PlantInfoDialog", "Số điện thoại"))
        self.phoneInput.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #bdc3c7; border-radius: 4px; font-size: 13px;"))
        self.phoneInput.setPlaceholderText(_translate("PlantInfoDialog", "Nhập số điện thoại"))
        self.emailLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.emailLabel.setText(_translate("PlantInfoDialog", "Email"))
        self.emailInput.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #bdc3c7; border-radius: 4px; font-size: 13px;"))
        self.emailInput.setPlaceholderText(_translate("PlantInfoDialog", "Nhập email"))
        self.positionLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.positionLabel.setText(_translate("PlantInfoDialog", "Chức vụ"))
        self.positionCombo.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #bdc3c7; border-radius: 4px; font-size: 13px;"))
        self.positionCombo.setItemText(0, _translate("PlantInfoDialog", "Trưởng phòng"))
        self.positionCombo.setItemText(1, _translate("PlantInfoDialog", "Phó phòng"))
        self.positionCombo.setItemText(2, _translate("PlantInfoDialog", "Chuyên viên"))
        self.positionCombo.setItemText(3, _translate("PlantInfoDialog", "Nhân viên"))
        self.positionCombo.setItemText(4, _translate("PlantInfoDialog", "Thực tập sinh"))
        self.areaLabel.setStyleSheet(_translate("PlantInfoDialog", "font-size: 13px; color: #2c3e50; min-width: 120px;"))
        self.areaLabel.setText(_translate("PlantInfoDialog", "Khu vực phụ trách"))
        self.areaInput.setStyleSheet(_translate("PlantInfoDialog", "padding: 8px; border: 2px solid #bdc3c7; border-radius: 4px; font-size: 13px;"))
        self.areaInput.setPlaceholderText(_translate("PlantInfoDialog", "Nhập khu vực phụ trách"))
        self.cancelButton.setStyleSheet(_translate("PlantInfoDialog", "\n"
"         QPushButton {\n"
"             background-color: #95a5a6;\n"
"             color: white;\n"
"             border: none;\n"
"             border-radius: 6px;\n"
"             font-weight: bold;\n"
"             font-size: 14px;\n"
"             padding: 10px;\n"
"         }\n"
"         QPushButton:hover {\n"
"             background-color: #7f8c8d;\n"
"         }\n"
"         QPushButton:pressed {\n"
"             background-color: #6c7a7a;\n"
"         }\n"
"        "))
        self.cancelButton.setText(_translate("PlantInfoDialog", "Hủy"))
        self.saveButton.setStyleSheet(_translate("PlantInfoDialog", "\n"
"         QPushButton {\n"
"             background-color: #27ae60;\n"
"             color: white;\n"
"             border: none;\n"
"             border-radius: 6px;\n"
"             font-weight: bold;\n"
"             font-size: 14px;\n"
"             padding: 10px;\n"
"         }\n"
"         QPushButton:hover {\n"
"             background-color: #219a52;\n"
"         }\n"
"         QPushButton:pressed {\n"
"             background-color: #1e8449;\n"
"         }\n"
"        "))
        self.saveButton.setText(_translate("PlantInfoDialog", "Lưu thông tin"))
