# Form implementation generated from reading ui file 'sign.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterForm(object):
    def setupUi(self, RegisterForm):
        RegisterForm.setObjectName("RegisterForm")
        RegisterForm.resize(565, 620)
        RegisterForm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(RegisterForm)
        self.verticalLayout.setContentsMargins(25, 30, 25, 25)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=RegisterForm)
        self.titleLabel.setStyleSheet("color: rgb(0, 85, 0);\n"
"border-image: url(:/images/ui/images/ngang.png);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(parent=RegisterForm)
        self.subtitleLabel.setStyleSheet("color: rgb(0, 85, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout.addWidget(self.subtitleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.mainFrame = QtWidgets.QFrame(parent=RegisterForm)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_2.setContentsMargins(20, 25, 20, 20)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_1 = QtWidgets.QLabel(parent=self.mainFrame)
        self.lbl_1.setStyleSheet("color: rgb(0, 85, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.lbl_1.setObjectName("lbl_1")
        self.verticalLayout_2.addWidget(self.lbl_1)
        self.txtFullName = QtWidgets.QLineEdit(parent=self.mainFrame)
        self.txtFullName.setStyleSheet("border-image: url(:/images/ui/images/ảnh cỏ.png);")
        self.txtFullName.setText("")
        self.txtFullName.setObjectName("txtFullName")
        self.verticalLayout_2.addWidget(self.txtFullName)
        self.lbl_2 = QtWidgets.QLabel(parent=self.mainFrame)
        self.lbl_2.setStyleSheet("color: rgb(0, 85, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.lbl_2.setObjectName("lbl_2")
        self.verticalLayout_2.addWidget(self.lbl_2)
        self.txtPhone = QtWidgets.QLineEdit(parent=self.mainFrame)
        self.txtPhone.setStyleSheet("border-image: url(:/images/ui/images/ảnh cỏ.png);")
        self.txtPhone.setText("")
        self.txtPhone.setObjectName("txtPhone")
        self.verticalLayout_2.addWidget(self.txtPhone)
        self.lbl_3 = QtWidgets.QLabel(parent=self.mainFrame)
        self.lbl_3.setStyleSheet("color: rgb(0, 85, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.lbl_3.setObjectName("lbl_3")
        self.verticalLayout_2.addWidget(self.lbl_3)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.mainFrame)
        self.txtPassword.setStyleSheet("border-image: url(:/images/ui/images/ảnh cỏ.png);")
        self.txtPassword.setText("")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.verticalLayout_2.addWidget(self.txtPassword)
        self.lbl_4 = QtWidgets.QLabel(parent=self.mainFrame)
        self.lbl_4.setStyleSheet("color: rgb(0, 85, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.lbl_4.setObjectName("lbl_4")
        self.verticalLayout_2.addWidget(self.lbl_4)
        self.txtConfirmPassword = QtWidgets.QLineEdit(parent=self.mainFrame)
        self.txtConfirmPassword.setStyleSheet("border-image: url(:/images/ui/images/ảnh cỏ.png);")
        self.txtConfirmPassword.setText("")
        self.txtConfirmPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.verticalLayout_2.addWidget(self.txtConfirmPassword)
        self.chkTerms = QtWidgets.QCheckBox(parent=self.mainFrame)
        self.chkTerms.setStyleSheet("color: rgb(0, 85, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.chkTerms.setChecked(True)
        self.chkTerms.setObjectName("chkTerms")
        self.verticalLayout_2.addWidget(self.chkTerms)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.registerButton = QtWidgets.QPushButton(parent=self.mainFrame)
        self.registerButton.setMinimumSize(QtCore.QSize(0, 42))
        self.registerButton.setStyleSheet("color: rgb(0, 85, 0);\n"
"border-image: url(:/images/ui/images/ảnh cỏ.png);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout_2.addWidget(self.registerButton)
        self.verticalLayout.addWidget(self.mainFrame)

        self.retranslateUi(RegisterForm)
        QtCore.QMetaObject.connectSlotsByName(RegisterForm)

    def retranslateUi(self, RegisterForm):
        _translate = QtCore.QCoreApplication.translate
        RegisterForm.setWindowTitle(_translate("RegisterForm", "Đăng ký"))
        self.titleLabel.setText(_translate("RegisterForm", "Đăng ký"))
        self.subtitleLabel.setText(_translate("RegisterForm", "Xin hãy nhập đầy đủ thông tin để đăng ký"))
        self.lbl_1.setText(_translate("RegisterForm", "Họ và tên *"))
        self.lbl_2.setText(_translate("RegisterForm", "Số điện thoại *"))
        self.lbl_3.setText(_translate("RegisterForm", "Mật khẩu *"))
        self.lbl_4.setText(_translate("RegisterForm", "Nhập lại mật khẩu *"))
        self.chkTerms.setText(_translate("RegisterForm", "Tôi đồng ý với các điều khoản sử dụng "))
        self.registerButton.setText(_translate("RegisterForm", "Đăng ký"))
